# Generated by Django 6.0.8 on 2026-09-27 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField(db_index=True, help_text='Normalized canonical URL identifying the problem uniquely.', max_length=500, unique=True)),
                ('platform', models.CharField(db_index=True, default='leetcode', help_text='Platform identifier (e.g., leetcode, hackerrank, codeforces, other).', max_length=50)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255)),
                ('problem_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Unknown', 'Unknown')], default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Problem',
                'verbose_name_plural': 'Global Problems',
                'ordering': ['problem_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], help_text='Optional user-specific difficulty override if user wants to customize difficulty.', max_length=20, null=True)),
                ('recognition_cue', models.TextField(blank=True, help_text='Observation trigger: how to recognize this problem or algorithmic approach.')),
                ('mistakes', models.TextField(blank=True, help_text='Edge case traps or mistakes made during problem solving.')),
                ('notes', models.TextField(blank=True, help_text='Personal implementation notes, key invariants, and takeaways.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patterns', models.ManyToManyField(blank=True, related_name='user_problems', to='core.pattern')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='core.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Problem',
                'verbose_name_plural': 'User Problems',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('reviewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('scheduled_days', models.IntegerField(default=0)),
                ('elapsed_days', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('user_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='core.userproblem')),
            ],
            options={
                'verbose_name': 'Review History',
                'verbose_name_plural': 'Review Histories',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='FSRSCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField(db_index=True)),
                ('stability', models.FloatField(default=0.0)),
                ('difficulty', models.FloatField(default=0.0)),
                ('elapsed_days', models.IntegerField(default=0)),
                ('scheduled_days', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('lapses', models.IntegerField(default=0)),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=0)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_card', to='core.userproblem')),
            ],
            options={
                'verbose_name': 'FSRS Card',
                'verbose_name_plural': 'FSRS Cards',
                'ordering': ['due'],
            },
        ),
    ]
