# Generated by Django 6.0.8 on 2026-09-27 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pattern_problem_userproblem_reviewhistory_fsrscard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproblem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pattern',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for predefined global patterns; set for custom user-created patterns.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproblem',
            name='user_difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', help_text='User-entered difficulty when problem is user-specific.', max_length=20),
        ),
        migrations.AddField(
            model_name='userproblem',
            name='user_title',
            field=models.CharField(blank=True, default='', help_text='User-entered title when problem is user-specific.', max_length=255),
        ),
        migrations.AddField(
            model_name='userproblem',
            name='user_url',
            field=models.URLField(blank=True, default='', help_text='Canonical URL for user-specific problems when not in global Problem table.', max_length=500),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userproblem',
            name='problem',
            field=models.ForeignKey(blank=True, help_text='Null if user-specific problem (not identified by LC API or slug).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='core.problem'),
        ),
        migrations.AddConstraint(
            model_name='pattern',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('slug',), name='unique_global_pattern_slug'),
        ),
        migrations.AddConstraint(
            model_name='pattern',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'slug'), name='unique_user_pattern_slug'),
        ),
        migrations.AddConstraint(
            model_name='userproblem',
            constraint=models.UniqueConstraint(condition=models.Q(('problem__isnull', False)), fields=('user', 'problem'), name='unique_user_global_problem'),
        ),
        migrations.AddConstraint(
            model_name='userproblem',
            constraint=models.UniqueConstraint(condition=models.Q(('problem__isnull', True)), fields=('user', 'user_url'), name='unique_user_specific_url'),
        ),
        migrations.RemoveField(
            model_name='userproblem',
            name='custom_difficulty',
        ),
    ]
