# Generated by Django 6.0.8 on 2026-09-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userproblem_unique_together_pattern_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsrscard',
            name='lapses',
        ),
        migrations.RemoveField(
            model_name='fsrscard',
            name='reps',
        ),
        migrations.AddField(
            model_name='fsrscard',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fsrscard',
            name='state',
            field=models.IntegerField(choices=[(1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=1),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
