# Generated by Django 6.0.8 on 2026-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_fsrscard_lapses_remove_fsrscard_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblem',
            name='mistakes',
            field=models.TextField(blank=True, help_text='Edge case traps or mistakes made during problem solving.', max_length=300),
        ),
        migrations.AlterField(
            model_name='userproblem',
            name='notes',
            field=models.TextField(blank=True, help_text='Personal implementation notes, key invariants, and takeaways.', max_length=600),
        ),
        migrations.AlterField(
            model_name='userproblem',
            name='recognition_cue',
            field=models.TextField(blank=True, help_text='Observation trigger: how to recognize this problem or algorithmic approach.', max_length=250),
        ),
    ]
